version: "3.9"
services:
  sports-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /Users/janeves/personalDev/rides_pgdata:/var/lib/postgresql/data/pgdata
